#define SYSCALL_BASE 0x200


#define SYSCALL_A_DATA0 "Hello\033" // non-printing char
#define SYSCALL_A_DATA1 ""  // empty string

#define SYSCALL_PICKTEST SYSCALL_BASE+0
#define SYSCALL_A SYSCALL_BASE+1
#define SYSCALL_B SYSCALL_BASE+2
#define SYSCALL_C SYSCALL_BASE+3
#define SYSCALL_D SYSCALL_BASE+4
#define SYSCALL_E SYSCALL_BASE+5
#define SYSCALL_F SYSCALL_BASE+6
#define SYSCALL_G SYSCALL_BASE+7
#define SYSCALL_H SYSCALL_BASE+8
#define SYSCALL_I SYSCALL_BASE+9
#define SYSCALL_J SYSCALL_BASE+10

